// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using index.AppData;

#nullable disable

namespace DotNet_Core.Migrations
{
    [DbContext(typeof(DBInteractor))]
    [Migration("20230426090605_firstinitialization")]
    partial class firstinitialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("users.AppData.UserInfo", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OTP_Pin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("avatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstname")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isLoogedIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
